# Generated by Django 5.0.6 on 2024-08-29 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length='1000')),
                ('avatar', models.ImageField(default='avatars_chat/default.png', upload_to='avatars_chat/')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('suc', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meow_messenger.group_chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meow_messenger.user')),
            ],
        ),
        migrations.AddField(
            model_name='group_chat',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='meow_messenger.user'),
        ),
        migrations.AddField(
            model_name='group_chat',
            name='users',
            field=models.ManyToManyField(related_name='users', to='meow_messenger.user'),
        ),
    ]
