# Generated by Django 5.0.6 on 2024-09-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meow_messenger', '0002_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_api',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
